---
#---------User Design Parameters---------
# Modify these following values to match your engine design parameters.
# NOTE: [~] indicates dimensionless parameters. Units default to SI units.
# NOTE: `null` indicates that the value is calculated, but can also be set.
# If there is [null] next to a value, that parameter can be set to `null`.
# The user should leave as `null` if he/she is unsure about the parameter.

#------------Main Parameters-------------
thrust   : null    # [N] [null] Thrust
of_ratio : 5.5     # [~] Oxidizer-to-fuel ratio
P_0      : 3.0e+06 # [Pa] Chamber pressure
altitude : 500     # [m] Operational altitude
frozen   : true    # [~] Frozen/equilibrium combustion
T_amb    : 300     # [K] Ambient temperature
Lstar    : 1.25    # [m] Mixing length

#---------Preliminary Parameters---------
est_isp : 200 # [s] [null] Estimated specific impulse (to approx. altitude)
target_alt : 5000 # [ft] [null] Target apogee altitude
min_rail_vel : 100 # [ft/s] [null] Minimum launch velocity off rail
rail_length : 16 # [ft] [null] Length of the launch rail

#------Runtime & Script Parameters-------
plot_on      : true
save_data_on : true

#-------Plumbing System Properties-------
ox: # Oxidizer (nitrous oxide) properties
  cv_type: 1 # Arrangement of valves; 0 = series, 1 = parallel
  valve_cvs: # [~] Array of valve flow coefficients (Cv), arranged via cv_type
    - 0.9 # Leave array empty/as zero if no propellant valves
    - 0.9
    - 0.9
  injector_area : 2.0e-04 # [m^2] [null] Total injector orifice area
  Cd_injector   : 0.9     # [~] Discharge coefficient (of injector orifices)
  V_tank        : 8       # [L] Propellant tank volume (around 60 cubic feet)
  # V_l           : null    # [L] [null] Liquid nitrous volume 
  V_l           : 4.5     # [L] 3.1621
  tank_id       : 7       # [in] Tank inner diameter
  h_offset_tank : 2       # [in] Distance from bottom of tank to injector
  d_flowline    : 0.5     # [in] Main flow line diameter
  T_tank        : 300     # [K] Tank temperature
ox_pressurant: # Properties for the gaseous oxidizer pressurant (nitrous)
  gas_properties : 0 # 0 = nitrogen, 1 = helium (more inert gases will be added later)
  set_pressure : 950 # [psi] Set regulator pressure between COPV and propellant tank
  storage_initial_pressure : 0 # [psi] Initial storage pressure of pressurant; 0 = off
  tank_volume : 0 # [L] Pressurant storage tank volume
  flow_CdA : 6.4e-5 # [m^2] CdA of flow between storage and propellant tank
  active: false # Supercharging; pressurizing ox above vapor pressure?

fuel: # Fuel (95% ethyl alcohol) properties
  cv_type: 0 # Arrangement of valves; 0 = series, 1 = parallel
  valve_cvs: # Leave array empty/as zero if no propellant valves
    - 0.9
  injector_area : 8.0e-06 # [m^2] [null] Total injector orifice area
  Cd_injector   : 0.88    # [~] Discharge coefficient (of injector orifices)
  V_tank        : 4       # [L] Propellant tank volume (around 30 cubic feet)
  # V_l           : null    # [L] [null] Liquid nitrous volume
  V_l           : 1.0     # [L] 0.4215
  tank_id       : 5       # [in] Tank inner diameter
  h_offset_tank : 2       # [in] Distance from bottom of tank to injector
  d_flowline    : 0.5     # [in] Main flow line diameter
  T_tank        : 300     # [K] Tank temperature
fuel_pressurant: # Properties for the gaseous oxidizer pressurant (nitrous)
  gas_properties : 0 # 0 = nitrogen, 1 = helium (more inert gases will be added later)
  set_pressure : 490 # [psi] Set regulator pressure between COPV and propellant tank
  storage_initial_pressure : 0 # [psi] Initial storage pressure of pressurant; 0 = off
  tank_volume : 0 # [L] Pressurant storage tank volume
  flow_CdA : 6.4e-05 # [m^2] CdA of flow between storage and propellant tank
  active: true # Supercharging; pressurizing ox above vapor pressure?

#---------Additional Properties----------
dt_valve_open   : 0.01 # [s] Main propellant valve opening cycle
mass_dry_rocket : 65   # [lbm] Dry mass of the rocket
# Combustion chamber dimensions
length_cc : null # [m]
d_cc      : null # [m]
# Estimated nozzle efficiency
nozzle_efficiency        : 0.95   # [~] Nozzle efficiency
nozzle_correction_factor : 0.9830 # [~] Nozzle correction factor
c_star_efficiency        : 0.85   # [~] Estimated combustion efficiency
d_throat                 : null   # [m] Nozzle throat diameter
exp_ratio                : null   # [~] Nozzle expansion ratio
# Fluid properties
rho_o : 772.75 # [kg/m^3] Density of oxidizer
rho_f : 789    # [kg/m^3] Density of fuel
# Injector parameters
delta_p : 25.0 # [%] Percent of injector/chamber dP
min_d_o : 2.00 # [mm] Minimum allowable diameter of oxidizer orifices
min_d_f : 1.00 # [mm] Minimum allowable diameter of fuel orifices
max_n_o : 40   # [~] Maximum allowable number of oxidizer orifices 
max_n_f : 40   # [~] Maximum allowable number of fuel orifices 

#-------PropSim Runtime Parameters-------
mode:
  combustion_on : true
  flight_on     : false
options:
  t_final   : 60
  dt        : 0.01
  output_on : null # Corresponds with (is equal to) `plot_on`
test_data:
  test_plots_on : false # Import tests data and plot against simulation data
  test_data_file : "5_13_18_data.mat"
  t_offset : 0 # [s] Time offset of test data with respect to simulation data
propsim_io:
  input_file : "PropSimInput" # This will be a .json file
  output_file : "PropSimOutput" # This will be a .mat file

#-----Standard Parameters/Constants-----
# These values are either well-established standards or numerical constants.
# Do not modify these values unless you are aware of their consequences.
imp_angle  : 60  # [deg] Orifice impingement angle
M_coeff    : 1.6 # [~] 2-on-1 doublet M coefficient
jet_LD     : 6   # [~] Jet length/diameter ratio
orifice_LD : 7   # [~] Orifice length/diameter ratio
cont_ratio : 8   # [~] Contraction ratio
